version: '3'

services:
    # https://hub.docker.com/r/yappabe/mailcatcher
    mailcatcher:
      image: yappabe/mailcatcher
      container_name: monblog-mailcatcher
      ports:
        - 1025:1025
        - 1080:1080

    # https://hub.docker.com/_/mariadb
    mariadb:
      image: mariadb
      restart: unless-stopped
      container_name: monblog_mariadb
      volumes:
        - ./mysql:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=monblog
    node:
      build: node
      container_name: monblog_node
      volumes:
        - ./web:/var/www/html/
      command: bash -c "yarn && yarn watch"
    # php - apache - centos
    php8-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: monblog_app
        depends_on:
            - mariadb
            - mailcatcher
        ports:
            - "8000:80"
        volumes:
            - ./web:/var/www/html/

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080